[package]
name = "nats-source-connector"
group = "lougc"
version = "0.1.0"
apiVersion = "0.1.0"
fluvio = "0.10.0"
description = ""
license = "Apache-2.0"
visibility = "public"

[direction]
 source = true 

[deployment]
binary = "nats-source-connector"

[custom.properties.foo]
title = "Foo"
description = "Foo"
type = "string"
